window.AUTOHUB_ENGINE_DATA = {
  records: [
    {
      id: 'volvo-b5202s', code: 'B5202S', aliases: ['B5202'], maker: 'Volvo', regionKey: 'europe', years: '1995-2000',
      displacement: '2.0 L · 1,984 cc', layout: 'I5 · SOHC · 10V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingBelt',
      applications: ['Volvo 850', 'Volvo S70', 'Volvo V70'], consumption: '8-12 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-450,000 km', oilRecord: 'volvo-s70-b5202s', statusKey: 'starterReview',
      text: {
        en: { construction: 'Volvo modular five-cylinder with an aluminium block, cast-iron liners, aluminium 10-valve head, multipoint injection and timing belt.', issues: 'Age-related PCV restriction and oil leaks; timing belt, idlers and water pump; cooling hoses and radiator; ignition and vacuum faults.', pros: 'Simple naturally aspirated layout, durable core, good repair knowledge and characteristic five-cylinder smoothness.', cons: 'Age now matters as much as mileage; belt service is critical and some parts or diagnostic procedures vary by market.' },
        es: { construction: 'Cinco cilindros modular Volvo con bloque de aluminio, camisas de hierro, culata de 10 válvulas, inyección multipunto y correa.', issues: 'PCV y fugas de aceite por edad; correa, rodillos y bomba de agua; manguitos y radiador; fallos de encendido y vacío.', pros: 'Diseño atmosférico sencillo, base duradera, reparación conocida y suavidad típica de cinco cilindros.', cons: 'La edad importa tanto como el kilometraje; la correa es crítica y algunas piezas o diagnósticos cambian según el mercado.' },
        fr: { construction: 'Cinq cylindres modulaire Volvo avec bloc aluminium, chemises fonte, culasse 10 soupapes, injection multipoint et courroie.', issues: 'PCV et fuites d’huile avec l’âge ; courroie, galets et pompe à eau ; durites et radiateur ; allumage et dépression.', pros: 'Architecture atmosphérique simple, base durable, réparations bien connues et souplesse du cinq cylindres.', cons: 'L’âge compte autant que le kilométrage ; la courroie est critique et certaines pièces ou méthodes varient selon le marché.' },
        de: { construction: 'Volvo-Fünfzylinder mit Aluminiumblock, Grauguss-Laufbuchsen, 10-Ventil-Kopf, Saugrohreinspritzung und Zahnriemen.', issues: 'Altersbedingte Kurbelgehäuseentlüftung und Öllecks; Zahnriemen, Rollen und Wasserpumpe; Kühlschläuche und Kühler; Zündung und Unterdruck.', pros: 'Einfacher Saugmotor, haltbarer Grundmotor, gute Reparaturkenntnis und typischer Fünfzylinderlauf.', cons: 'Alter ist so wichtig wie Laufleistung; der Zahnriemenservice ist kritisch und Teile oder Diagnose unterscheiden sich nach Markt.' }
      }
    },
    {
      id: 'bmw-m54', code: 'M54', aliases: ['M54B22', 'M54B25', 'M54B30'], maker: 'BMW', regionKey: 'europe', years: '2000-2006',
      displacement: '2.2-3.0 L', layout: 'I6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['BMW 3 Series E46', '5 Series E39 / E60', 'X3 E83', 'X5 E53', 'Z4 E85'], consumption: '8-13 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: 'bmw-e46-m54', statusKey: 'starterReview',
      text: {
        en: { construction: 'Aluminium inline-six with a 24-valve DOHC head, double VANOS, multipoint injection and chain-driven camshafts.', issues: 'Cooling-system plastics and water pump; CCV system; DISA valve; VANOS seals; oil-filter housing and valve-cover leaks; oil consumption.', pros: 'Very smooth, strong parts support, good diagnostics and a durable core when overheating is avoided.', cons: 'Cooling neglect can damage the aluminium head; several age-related oil and vacuum leaks often appear together.' },
        es: { construction: 'Seis cilindros en línea de aluminio con culata DOHC de 24 válvulas, doble VANOS, inyección multipunto y cadena.', issues: 'Plásticos de refrigeración y bomba; sistema CCV; válvula DISA; sellos VANOS; fugas en filtro y tapa; consumo de aceite.', pros: 'Muy suave, muchas piezas, buen diagnóstico y base duradera si no se sobrecalienta.', cons: 'Descuidar la refrigeración puede dañar la culata; varias fugas de aceite y vacío suelen aparecer juntas.' },
        fr: { construction: 'Six cylindres en ligne aluminium, culasse DOHC 24 soupapes, double VANOS, injection multipoint et chaîne.', issues: 'Plastiques du refroidissement et pompe ; CCV ; valve DISA ; joints VANOS ; fuites boîtier de filtre et couvre-culasse ; consommation d’huile.', pros: 'Très souple, pièces nombreuses, bon diagnostic et base durable sans surchauffe.', cons: 'Une surchauffe peut endommager la culasse ; plusieurs fuites d’huile et de dépression apparaissent souvent ensemble.' },
        de: { construction: 'Aluminium-Reihensechszylinder mit 24-Ventil-DOHC-Kopf, Doppel-VANOS, Saugrohreinspritzung und Steuerkette.', issues: 'Kühlsystem-Kunststoffe und Wasserpumpe; KGE; DISA; VANOS-Dichtungen; Ölfiltergehäuse und Ventildeckel; Ölverbrauch.', pros: 'Sehr laufruhig, gute Teilelage und Diagnose, haltbarer Grundmotor ohne Überhitzung.', cons: 'Kühlungsvernachlässigung kann den Aluminiumkopf schädigen; Öl- und Unterdrucklecks treten oft gemeinsam auf.' }
      }
    },
    {
      id: 'vw-ea888', code: 'EA888', aliases: ['1.8 TSI', '2.0 TSI', '1.8 TFSI', '2.0 TFSI'], maker: 'Volkswagen Group', regionKey: 'europe', years: '2007-present',
      displacement: '1.8-2.0 L', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'turbocharged',
      injectionKey: 'directInjection', blockKey: 'castIronBlock', timingKey: 'timingChain',
      applications: ['VW Golf / Passat / Tiguan', 'Audi A3 / A4 / Q5', 'Skoda Octavia', 'SEAT Leon'], consumption: '6.5-11 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '200,000-350,000 km', oilRecord: 'vw-golf-ea888', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Turbocharged direct-injection family with several generations. Most versions use an iron block, aluminium 16-valve head, variable timing and chain drive.', issues: 'Early chain tensioners; oil consumption on some Gen 1/2 versions; water-pump and thermostat module; PCV; intake-valve carbon deposits.', pros: 'Strong low-speed torque, good efficiency, huge parts supply and broad diagnostic support.', cons: 'Problems differ sharply by generation and engine code; neglected examples can become expensive quickly.' },
        es: { construction: 'Familia turbo de inyección directa con varias generaciones. La mayoría usa bloque de hierro, culata de aluminio de 16 válvulas, distribución variable y cadena.', issues: 'Tensores tempranos; consumo de aceite en algunos Gen 1/2; módulo de bomba y termostato; PCV; carbón en admisión.', pros: 'Mucho par a bajas rpm, buena eficiencia, enorme oferta de piezas y diagnóstico.', cons: 'Los problemas cambian mucho por generación y código; el abandono puede resultar caro rápidamente.' },
        fr: { construction: 'Famille turbo à injection directe sur plusieurs générations. La plupart ont bloc fonte, culasse aluminium 16 soupapes, calage variable et chaîne.', issues: 'Tendeurs précoces ; consommation d’huile sur certains Gen 1/2 ; pompe à eau et thermostat ; PCV ; calamine admission.', pros: 'Fort couple à bas régime, bonne efficacité, pièces nombreuses et diagnostic étendu.', cons: 'Les problèmes changent fortement selon génération et code ; un entretien négligé devient vite coûteux.' },
        de: { construction: 'Turbo-Direkteinspritzerfamilie in mehreren Generationen. Meist Graugussblock, Aluminium-16V-Kopf, variable Steuerzeiten und Kette.', issues: 'Frühe Kettenspanner; Ölverbrauch bei manchen Gen 1/2; Wasserpumpen-Thermostatmodul; PCV; Einlassverkokung.', pros: 'Starkes Drehmoment, gute Effizienz, sehr gute Teile- und Diagnoseunterstützung.', cons: 'Probleme unterscheiden sich stark nach Generation und Motorkennbuchstabe; Wartungsstau wird schnell teuer.' }
      }
    },
    {
      id: 'toyota-1zz-fe', code: '1ZZ-FE', aliases: ['1ZZ'], maker: 'Toyota', regionKey: 'japan', years: '1998-2007',
      displacement: '1.8 L · 1,794 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Toyota Corolla', 'Avensis', 'Celica', 'MR2', 'Pontiac Vibe'], consumption: '6.5-9.5 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: 'toyota-corolla-1zz', statusKey: 'starterReview',
      text: {
        en: { construction: 'Light aluminium 1.8-litre four-cylinder with a 16-valve head, VVT-i, multipoint injection and timing chain.', issues: 'Oil-control ring design and oil consumption on early engines; chain tensioner leaks; water pump; overheating damage on neglected cars.', pros: 'Economical, simple, globally common and supported by inexpensive service parts.', cons: 'Early oil use can become severe; the thin-liner block is not intended for a traditional simple rebore.' },
        es: { construction: 'Cuatro cilindros ligero de aluminio, 1.8 litros, culata de 16 válvulas, VVT-i, inyección multipunto y cadena.', issues: 'Segmentos y consumo de aceite en motores tempranos; fuga del tensor; bomba de agua; daños por sobrecalentamiento.', pros: 'Económico, sencillo, común en todo el mundo y con repuestos asequibles.', cons: 'El consumo temprano puede ser grave; el bloque de camisas finas no está pensado para un rectificado tradicional sencillo.' },
        fr: { construction: 'Quatre cylindres aluminium léger de 1,8 litre, culasse 16 soupapes, VVT-i, injection multipoint et chaîne.', issues: 'Segments racleurs et consommation d’huile sur premiers moteurs ; fuite tendeur ; pompe à eau ; dégâts de surchauffe.', pros: 'Économique, simple, très répandu et pièces d’entretien abordables.', cons: 'La consommation d’huile peut devenir forte ; le bloc à chemises fines ne se réalèse pas simplement de façon traditionnelle.' },
        de: { construction: 'Leichter 1,8-Liter-Aluminium-Vierzylinder mit 16V-Kopf, VVT-i, Saugrohreinspritzung und Steuerkette.', issues: 'Ölabstreifringe und Ölverbrauch früher Motoren; undichter Kettenspanner; Wasserpumpe; Überhitzungsschäden.', pros: 'Sparsam, einfach, weltweit verbreitet und günstige Serviceteile.', cons: 'Früher Ölverbrauch kann stark werden; der dünnwandige Block ist nicht für einfaches klassisches Aufbohren ausgelegt.' }
      }
    },
    {
      id: 'honda-k20', code: 'K20', aliases: ['K20A', 'K20A2', 'K20Z', 'K20C'], maker: 'Honda', regionKey: 'japan', years: '2000-present',
      displacement: '2.0 L', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'variantDependent',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Honda Civic', 'Accord', 'CR-V', 'Acura RSX', 'Integra'], consumption: '7-12 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-500,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Broad aluminium 2.0-litre DOHC i-VTEC family. Early versions are naturally aspirated and port-injected; later K20C versions can use direct injection and turbocharging.', issues: 'Valve-clearance neglect; oil leaks; VTC actuator noise; chain or tensioner wear with poor oil service; damage from bad tuning or over-revving.', pros: 'Strong core, excellent breathing, large parts market and very good performance potential.', cons: 'K20 is a family, not one specification; output, injection, turbocharging and failure patterns vary greatly by suffix.' },
        es: { construction: 'Amplia familia 2.0 de aluminio, DOHC e i-VTEC. Los primeros son atmosféricos e indirectos; K20C posteriores pueden ser turbo e inyección directa.', issues: 'Holgura de válvulas; fugas; ruido del actuador VTC; cadena o tensor con aceite descuidado; daños por mal tuning o exceso de rpm.', pros: 'Base fuerte, buena respiración, enorme mercado de piezas y gran potencial.', cons: 'K20 es una familia, no una sola especificación; potencia, inyección, turbo y fallos cambian mucho según el sufijo.' },
        fr: { construction: 'Large famille 2,0 litres aluminium DOHC i-VTEC. Premières versions atmosphériques et indirectes ; K20C récents parfois turbo et injection directe.', issues: 'Jeu aux soupapes ; fuites ; bruit actuateur VTC ; chaîne ou tendeur avec huile négligée ; dégâts dus au mauvais tuning ou surrégime.', pros: 'Base solide, excellente respiration, marché de pièces énorme et fort potentiel.', cons: 'K20 est une famille, pas une spécification unique ; puissance, injection, turbo et pannes varient selon le suffixe.' },
        de: { construction: 'Breite 2,0-Liter-Aluminium-DOHC-i-VTEC-Familie. Frühe Motoren sind Saugrohreinspritzer, spätere K20C teils Direkteinspritzer mit Turbo.', issues: 'Vernachlässigtes Ventilspiel; Öllecks; VTC-Stellerrasseln; Kette oder Spanner bei schlechtem Ölservice; Schäden durch Tuning oder Überdrehen.', pros: 'Starker Grundmotor, guter Gaswechsel, riesiger Teilemarkt und hohes Leistungspotenzial.', cons: 'K20 ist eine Familie, keine Einzelspezifikation; Leistung, Einspritzung, Turbo und Fehler unterscheiden sich stark nach Suffix.' }
      }
    },
    {
      id: 'nissan-qr25de', code: 'QR25DE', aliases: ['QR25'], maker: 'Nissan', regionKey: 'japan', years: '2001-present',
      displacement: '2.5 L · 2,488 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Nissan Altima', 'X-Trail', 'Rogue', 'Sentra SE-R', 'Frontier'], consumption: '8-12 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Long-running aluminium 2.5-litre four-cylinder family with DOHC head and timing chain. Injection and detail design changed across generations.', issues: 'Early pre-catalyst damage and oil use; early intake butterfly screws; chain wear; overheating and head-gasket damage; later-version issues differ.', pros: 'Good low-speed torque, wide global use, accessible parts and straightforward basic service.', cons: 'Early and late QR25DE versions must not be treated as identical; vehicle CVT problems are often confused with engine faults.' },
        es: { construction: 'Familia 2.5 de aluminio de larga producción con culata DOHC y cadena. La inyección y detalles cambiaron por generación.', issues: 'Precatalizador y consumo en versiones tempranas; tornillos de admisión; cadena; sobrecalentamiento y junta; otros fallos en versiones posteriores.', pros: 'Buen par a bajas rpm, uso mundial, piezas accesibles y mantenimiento básico sencillo.', cons: 'Las versiones tempranas y tardías no son iguales; problemas de CVT se confunden a menudo con fallos del motor.' },
        fr: { construction: 'Famille aluminium 2,5 litres produite longtemps, culasse DOHC et chaîne. Injection et détails ont évolué selon génération.', issues: 'Pré-catalyseur et consommation d’huile sur premières versions ; vis de papillons ; chaîne ; surchauffe et joint de culasse ; défauts ultérieurs différents.', pros: 'Bon couple à bas régime, diffusion mondiale, pièces accessibles et entretien courant simple.', cons: 'Versions anciennes et récentes ne sont pas identiques ; les défauts de CVT sont souvent confondus avec le moteur.' },
        de: { construction: 'Langjährig gebaute 2,5-Liter-Aluminium-Vierzylinderfamilie mit DOHC-Kopf und Kette. Einspritzung und Details änderten sich je Generation.', issues: 'Frühe Vorkatalysator- und Ölverbrauchsprobleme; Ansaugklappenschrauben; Kette; Überhitzung und Kopfdichtung; spätere Varianten anders.', pros: 'Gutes Drehmoment, weltweit verbreitet, verfügbare Teile und einfacher Grundservice.', cons: 'Frühe und späte QR25DE sind nicht gleich; CVT-Probleme werden oft mit Motorfehlern verwechselt.' }
      }
    },
    {
      id: 'hyundai-g4kd', code: 'G4KD', aliases: ['Theta II 2.0 MPI'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2008-2020',
      displacement: '2.0 L · 1,998 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Sonata / ix35', 'Kia Sportage / Optima', 'Mitsubishi-related platforms'], consumption: '7.5-11 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '150,000-300,000 km', oilRecord: '', statusKey: 'recallCheck',
      text: {
        en: { construction: 'Theta II 2.0-litre aluminium four-cylinder with DOHC head, dual CVVT, multipoint injection and timing chain.', issues: 'Rod-bearing or cylinder-scuffing complaints in some markets; oil consumption; chain wear; catalyst debris concerns; recall and campaign coverage varies by VIN.', pros: 'Simple MPI equipment, broad parts availability and good everyday performance when healthy.', cons: 'Condition varies widely; VIN recall history, cold noise, oil level and compression deserve special attention.' },
        es: { construction: 'Theta II 2.0 de aluminio con culata DOHC, doble CVVT, inyección multipunto y cadena.', issues: 'Cojinetes o rayado de cilindros en algunos mercados; consumo de aceite; cadena; residuos de catalizador; campañas según VIN.', pros: 'Equipo MPI sencillo, muchas piezas y buen uso diario cuando está sano.', cons: 'El estado varía mucho; historial de campañas, ruido en frío, nivel de aceite y compresión requieren atención.' },
        fr: { construction: 'Theta II 2,0 litres aluminium, culasse DOHC, double CVVT, injection multipoint et chaîne.', issues: 'Coussinets ou rayures de cylindres selon marchés ; consommation d’huile ; chaîne ; débris de catalyseur ; campagnes selon VIN.', pros: 'Équipement MPI simple, pièces nombreuses et bonnes performances quotidiennes en bon état.', cons: 'État très variable ; historique des campagnes, bruit à froid, niveau d’huile et compression sont essentiels.' },
        de: { construction: 'Theta-II-2,0-Liter-Aluminium-Vierzylinder mit DOHC, Doppel-CVVT, Saugrohreinspritzung und Kette.', issues: 'Pleuellager- oder Zylinderriefenmeldungen je Markt; Ölverbrauch; Kette; Katalysatorpartikel; Aktionen je VIN unterschiedlich.', pros: 'Einfache MPI-Technik, gute Teileverfügbarkeit und ordentliche Alltagsleistung bei gesundem Motor.', cons: 'Zustand schwankt stark; Rückrufhistorie, Kaltgeräusch, Ölstand und Kompression besonders prüfen.' }
      }
    },
    {
      id: 'hyundai-g4fg', code: 'G4FG', aliases: ['Gamma 1.6'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2010-present',
      displacement: '1.6 L · 1,591 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Accent / Elantra / i30', 'Kia Rio / Ceed / Soul'], consumption: '6-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '200,000-350,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Gamma-family aluminium 1.6-litre engine with DOHC head, dual CVVT and timing chain. MPI and GDI versions require separate identification.', issues: 'Oil consumption with wear; chain noise; catalyst or cylinder-scuffing reports in some markets; intake deposits on GDI versions; valve-clearance neglect.', pros: 'Economical, compact, widely used and supported by affordable parts.', cons: 'MPI and GDI service needs differ; market-specific catalyst and recall history should be checked by VIN.' },
        es: { construction: 'Motor Gamma 1.6 de aluminio con culata DOHC, doble CVVT y cadena. Las versiones MPI y GDI deben identificarse por separado.', issues: 'Consumo con desgaste; ruido de cadena; catalizador o rayado en algunos mercados; depósitos en GDI; holgura de válvulas.', pros: 'Económico, compacto, muy usado y con piezas asequibles.', cons: 'MPI y GDI requieren mantenimiento diferente; revisa por VIN catalizador y campañas del mercado.' },
        fr: { construction: 'Moteur Gamma 1,6 litre aluminium, culasse DOHC, double CVVT et chaîne. Versions MPI et GDI à identifier séparément.', issues: 'Consommation avec usure ; bruit de chaîne ; catalyseur ou rayures selon marchés ; dépôts sur GDI ; jeu aux soupapes.', pros: 'Économique, compact, très répandu et pièces abordables.', cons: 'MPI et GDI ont des besoins différents ; vérifier catalyseur et campagnes par VIN.' },
        de: { construction: 'Gamma-1,6-Liter-Aluminiummotor mit DOHC, Doppel-CVVT und Kette. MPI- und GDI-Versionen getrennt identifizieren.', issues: 'Ölverbrauch bei Verschleiß; Kettengeräusch; Katalysator- oder Riefenmeldungen je Markt; GDI-Ablagerungen; Ventilspiel.', pros: 'Sparsam, kompakt, weit verbreitet und günstige Teile.', cons: 'MPI und GDI haben unterschiedliche Wartung; marktbezogene Katalysator- und Aktionshistorie per VIN prüfen.' }
      }
    },
    {
      id: 'hyundai-d4ha', code: 'D4HA', aliases: ['R 2.0 CRDi'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2009-present',
      displacement: '2.0 L · 1,995 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'diesel', aspirationKey: 'turbocharged',
      injectionKey: 'commonRail', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Santa Fe / ix35 / Tucson', 'Kia Sportage / Sorento'], consumption: '5.5-8.5 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'starterReview',
      text: {
        en: { construction: 'R-series 2.0-litre common-rail turbodiesel with DOHC head, variable-geometry turbo, chain drive and emissions equipment depending on market.', issues: 'DPF and EGR loading from short trips; intake deposits; injector correction; turbo oil supply; chain noise; cooling and boost leaks.', pros: 'Strong torque, good long-distance economy and broad use in SUVs.', cons: 'Emissions and injection repairs can be expensive; repeated short trips are a poor operating pattern.' },
        es: { construction: 'Diésel R 2.0 common-rail con culata DOHC, turbo de geometría variable, cadena y emisiones según mercado.', issues: 'Carga de DPF y EGR por trayectos cortos; depósitos; corrección de inyectores; aceite del turbo; cadena; fugas de refrigeración y presión.', pros: 'Buen par, consumo en carretera y uso amplio en SUV.', cons: 'Emisiones e inyección pueden ser caras; los trayectos cortos repetidos son un uso desfavorable.' },
        fr: { construction: 'Turbodiesel R 2,0 litres common rail, culasse DOHC, turbo à géométrie variable, chaîne et dépollution selon marché.', issues: 'Charge DPF/EGR sur petits trajets ; dépôts admission ; corrections injecteurs ; huile turbo ; chaîne ; fuites refroidissement et suralimentation.', pros: 'Fort couple, bonne sobriété routière et large usage en SUV.', cons: 'Dépollution et injection peuvent coûter cher ; les petits trajets répétés lui conviennent mal.' },
        de: { construction: 'R-2,0-Liter-Common-Rail-Turbodiesel mit DOHC, VTG-Lader, Kette und marktabhängiger Abgasnachbehandlung.', issues: 'DPF/EGR-Beladung bei Kurzstrecke; Ansaugablagerungen; Injektorkorrektur; Turboölversorgung; Kette; Kühl- und Ladedrucklecks.', pros: 'Starkes Drehmoment, guter Langstreckenverbrauch und breite SUV-Nutzung.', cons: 'Abgas- und Einspritzreparaturen können teuer sein; häufige Kurzstrecke ist ungünstig.' }
      }
    },
    {
      id: 'gm-lm7', code: 'LM7', aliases: ['Vortec 5300', '5.3 Vortec'], maker: 'General Motors', regionKey: 'usa', years: '1999-2007',
      displacement: '5.3 L · 5,328 cc', layout: 'V8 · OHV · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'castIronBlock', timingKey: 'timingChain',
      applications: ['Chevrolet Silverado / Tahoe / Suburban', 'GMC Sierra / Yukon'], consumption: '12-18 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '350,000-500,000 km', oilRecord: '', statusKey: 'starterReview',
      text: {
        en: { construction: 'Gen III small-block 5.3-litre pushrod V8 with iron block, aluminium heads, multipoint injection and a compact chain-driven camshaft.', issues: 'Knock-sensor water intrusion; broken exhaust-manifold bolts; intake and oil leaks; fuel-pump and ignition wear; oil pressure at high mileage.', pros: 'Simple layout, strong low-speed torque, huge North American parts supply and high-mileage potential.', cons: 'Fuel use is high; truck condition and cooling history matter, and neglected accessories can create many smaller repairs.' },
        es: { construction: 'V8 small-block Gen III de 5.3 litros, varillas, bloque de hierro, culatas de aluminio, inyección multipunto y cadena compacta.', issues: 'Agua en sensores de detonación; tornillos de escape; fugas de admisión y aceite; bomba e ignición; presión de aceite con muchos km.', pros: 'Diseño simple, mucho par, enorme oferta de piezas en Norteamérica y alto kilometraje posible.', cons: 'Consumo alto; importan el estado del camión y refrigeración, y los accesorios descuidados generan muchas reparaciones menores.' },
        fr: { construction: 'V8 small-block Gen III 5,3 litres à tiges, bloc fonte, culasses aluminium, injection multipoint et distribution compacte par chaîne.', issues: 'Eau aux capteurs de cliquetis ; vis de collecteur cassées ; fuites admission et huile ; pompe et allumage ; pression d’huile à fort kilométrage.', pros: 'Architecture simple, fort couple, pièces très nombreuses en Amérique du Nord et potentiel kilométrique élevé.', cons: 'Consommation élevée ; état du véhicule et refroidissement comptent, accessoires négligés créent de petites réparations.' },
        de: { construction: 'Gen-III-5,3-Liter-Small-Block-V8 mit Stößelstangen, Graugussblock, Aluminiumköpfen, MPI und kompakter Kettensteuerung.', issues: 'Wasser an Klopfsensoren; gebrochene Krümmerbolzen; Ansaug- und Öllecks; Kraftstoffpumpe und Zündung; Öldruck bei hoher Laufleistung.', pros: 'Einfacher Aufbau, starkes Drehmoment, riesige Teileversorgung in Nordamerika und hohe Laufleistung möglich.', cons: 'Hoher Verbrauch; Fahrzeugzustand und Kühlung zählen, vernachlässigte Nebenaggregate verursachen viele kleinere Reparaturen.' }
      }
    },
    {
      id: 'ford-coyote', code: '5.0 Coyote', aliases: ['Coyote', '5.0 Ti-VCT'], maker: 'Ford', regionKey: 'usa', years: '2011-present',
      displacement: '5.0 L', layout: 'V8 · DOHC · 32V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Ford Mustang GT', 'F-150 5.0'], consumption: '10-16 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 5.0-litre DOHC 32-valve V8 with Ti-VCT and chain drive. Injection, cylinder liners and detail design changed through generations.', issues: 'Water pump; VCT and timing noise; oil consumption on some versions; generation-specific cylinder or liner concerns; abuse and poor tuning.', pros: 'High specific output, strong aftermarket, good breathing and broad parts support.', cons: 'Generations are technically different; modified cars require careful calibration and service-history checks.' },
        es: { construction: 'V8 5.0 de aluminio, DOHC 32 válvulas, Ti-VCT y cadena. Inyección, camisas y detalles cambiaron por generación.', issues: 'Bomba de agua; ruido VCT y distribución; consumo en algunas versiones; cilindros o camisas según generación; abuso y mal tuning.', pros: 'Alta potencia específica, enorme aftermarket, buena respiración y piezas.', cons: 'Las generaciones son técnicamente distintas; coches modificados requieren revisar calibración e historial.' },
        fr: { construction: 'V8 aluminium 5,0 litres DOHC 32 soupapes, Ti-VCT et chaîne. Injection, chemises et détails évoluent selon génération.', issues: 'Pompe à eau ; bruit VCT et distribution ; consommation sur certaines versions ; cylindres ou chemises selon génération ; mauvais tuning.', pros: 'Puissance spécifique élevée, grand aftermarket, bonne respiration et pièces nombreuses.', cons: 'Les générations sont techniquement différentes ; les voitures modifiées exigent contrôle de calibration et historique.' },
        de: { construction: '5,0-Liter-Aluminium-DOHC-32V-V8 mit Ti-VCT und Kette. Einspritzung, Laufbahnen und Details änderten sich je Generation.', issues: 'Wasserpumpe; VCT- und Steuergeräusche; Ölverbrauch bei manchen Versionen; generationsbezogene Zylinderfragen; Missbrauch und schlechtes Tuning.', pros: 'Hohe spezifische Leistung, großer Zubehörmarkt, guter Gaswechsel und Teileversorgung.', cons: 'Generationen sind technisch verschieden; modifizierte Autos brauchen genaue Kalibrierungs- und Historienprüfung.' }
      }
    },
    {
      id: 'chrysler-pentastar', code: '3.6 Pentastar', aliases: ['Pentastar V6', 'ERB'], maker: 'Chrysler / Stellantis', regionKey: 'usa', years: '2011-present',
      displacement: '3.6 L · 3,604 cc', layout: 'V6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Jeep Wrangler / Grand Cherokee', 'Dodge Charger / Durango', 'Chrysler 300', 'Ram 1500'], consumption: '9-14 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 3.6-litre DOHC 24-valve V6 with variable timing, multipoint injection and chain-driven camshafts.', issues: 'Early left-cylinder-head issues; rocker and cam wear; plastic oil-cooler and filter housing leaks; water pump; cooling-system air or leaks.', pros: 'Widely used, good power for size, many service parts and no turbo on most applications.', cons: 'Oil-cooler housing and valvetrain repairs can be labour-intensive; vehicle packaging changes access significantly.' },
        es: { construction: 'V6 3.6 de aluminio, DOHC 24 válvulas, distribución variable, inyección multipunto y cadenas.', issues: 'Culata izquierda temprana; balancines y levas; fugas en enfriador y carcasa de filtro plásticos; bomba; aire o fugas de refrigeración.', pros: 'Muy usado, buena potencia, muchas piezas y sin turbo en la mayoría.', cons: 'Enfriador y distribución pueden requerir mucha mano de obra; el acceso cambia mucho según el vehículo.' },
        fr: { construction: 'V6 aluminium 3,6 litres DOHC 24 soupapes, calage variable, injection multipoint et arbres entraînés par chaînes.', issues: 'Culasse gauche sur premières séries ; culbuteurs et cames ; boîtier plastique refroidisseur-filtre ; pompe ; air ou fuites de refroidissement.', pros: 'Très répandu, bonne puissance, pièces nombreuses et sans turbo dans la plupart des applications.', cons: 'Refroidisseur et distribution peuvent demander beaucoup de main-d’œuvre ; l’accès varie fortement selon véhicule.' },
        de: { construction: '3,6-Liter-Aluminium-DOHC-24V-V6 mit variablen Steuerzeiten, MPI und kettengetriebenen Nockenwellen.', issues: 'Früher linker Zylinderkopf; Kipphebel und Nocken; Kunststoff-Ölkühler-Filtergehäuse; Wasserpumpe; Luft oder Lecks im Kühlsystem.', pros: 'Weit verbreitet, gute Leistung, viele Serviceteile und meist ohne Turbo.', cons: 'Ölkühlergehäuse und Ventiltrieb können arbeitsintensiv sein; Einbauraum unterscheidet sich stark nach Fahrzeug.' }
      }
    },
    {
      id: 'volvo-b5244s', code: 'B5244S', aliases: ['B5244S2', '2.4 Volvo'], maker: 'Volvo', regionKey: 'europe', years: '1999-2010',
      displacement: '2.4 L · 2,435 cc', layout: 'I5 · DOHC · 20V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingBelt',
      applications: ['Volvo S60', 'S70 / V70', 'S80', 'XC70'], consumption: '8-12 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-500,000 km', oilRecord: '', statusKey: 'starterReview',
      text: {
        en: { construction: 'Volvo modular 2.4-litre five-cylinder with aluminium block and head, 20 valves, multipoint injection, variable timing on some versions and timing belt.', issues: 'PCV restriction and oil leaks; electronic throttle on early cars; timing belt and rollers; VVT hub seals; cooling and ignition components.', pros: 'Smooth, durable, widely understood and generally less stressed than turbo versions.', cons: 'Age-related rubber, wiring and ventilation faults accumulate; exact suffix and throttle generation matter.' },
        es: { construction: 'Cinco cilindros modular Volvo 2.4 con bloque y culata de aluminio, 20 válvulas, inyección multipunto, distribución variable en algunas versiones y correa.', issues: 'PCV y fugas; mariposa electrónica temprana; correa y rodillos; retenes VVT; refrigeración y encendido.', pros: 'Suave, duradero, bien conocido y normalmente menos exigido que los turbo.', cons: 'Se acumulan fallos de goma, cableado y ventilación por edad; importan sufijo y generación de mariposa.' },
        fr: { construction: 'Cinq cylindres modulaire Volvo 2,4 litres, bloc et culasse aluminium, 20 soupapes, injection multipoint, calage variable selon version et courroie.', issues: 'PCV et fuites ; papillon électronique précoce ; courroie et galets ; joints VVT ; refroidissement et allumage.', pros: 'Souple, durable, bien connu et généralement moins sollicité que les turbos.', cons: 'Caoutchouc, câblage et ventilation vieillissent ; suffixe exact et génération de papillon comptent.' },
        de: { construction: 'Volvo-2,4-Liter-Fünfzylinder mit Aluminiumblock und -kopf, 20 Ventilen, MPI, teils variablen Steuerzeiten und Zahnriemen.', issues: 'KGE und Öllecks; frühe elektronische Drosselklappe; Zahnriemen und Rollen; VVT-Dichtungen; Kühlung und Zündung.', pros: 'Laufruhig, haltbar, gut bekannt und meist weniger belastet als Turboversionen.', cons: 'Altersbedingte Gummi-, Kabel- und Entlüftungsfehler sammeln sich; Suffix und Drosselklappengeneration zählen.' }
      }
    },
    {
      id: 'volvo-d5244t', code: 'D5244T / D5', aliases: ['D5', 'D5244T4', 'D5244T10', 'D5244T15'], maker: 'Volvo', regionKey: 'europe', years: '2001-2017',
      displacement: '2.4 L · 2,401 cc', layout: 'I5 · DOHC · 20V', fuelKey: 'diesel', aspirationKey: 'turbocharged',
      injectionKey: 'commonRail', blockKey: 'aluminumLiners', timingKey: 'timingBelt',
      applications: ['Volvo S60 / V60', 'S80', 'V70 / XC70', 'XC60', 'XC90'], consumption: '5.5-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-500,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Volvo-designed 2.4-litre common-rail five-cylinder turbodiesel with aluminium construction, timing belt and emissions equipment that changed by generation.', issues: 'Injectors and correction values; EGR and intake deposits; DPF on later cars; swirl mechanism on some versions; vacuum, turbo and belt-service faults.', pros: 'Strong torque, good long-distance economy and high-mileage capability with correct service.', cons: 'Many suffixes exist and emissions hardware differs; short trips and delayed belt or injector work become expensive.' },
        es: { construction: 'Turbodiésel Volvo 2.4 de cinco cilindros, common rail, aluminio, correa y emisiones que cambian por generación.', issues: 'Inyectores y correcciones; EGR y admisión; DPF posterior; mecanismo swirl en algunas versiones; vacío, turbo y correa.', pros: 'Mucho par, buen consumo en carretera y capacidad de alto kilometraje con mantenimiento.', cons: 'Hay muchos sufijos y sistemas de emisiones; trayectos cortos y retrasar correa o inyectores resulta caro.' },
        fr: { construction: 'Turbodiesel Volvo 2,4 litres cinq cylindres common rail, construction aluminium, courroie et dépollution variable selon génération.', issues: 'Injecteurs et corrections ; EGR et admission ; DPF récent ; volets selon versions ; dépression, turbo et entretien courroie.', pros: 'Fort couple, bonne économie routière et potentiel kilométrique élevé avec entretien.', cons: 'Nombreux suffixes et dépollutions différentes ; petits trajets et retard courroie ou injecteurs coûtent cher.' },
        de: { construction: 'Volvo-2,4-Liter-Fünfzylinder-Common-Rail-Turbodiesel in Leichtmetallbauweise mit Zahnriemen und generationsabhängiger Abgastechnik.', issues: 'Injektoren und Korrekturwerte; EGR und Ansaugung; später DPF; teils Drallklappen; Unterdruck, Turbo und Riemenservice.', pros: 'Starkes Drehmoment, guter Langstreckenverbrauch und hohe Laufleistung bei korrektem Service.', cons: 'Viele Suffixe und Abgasvarianten; Kurzstrecke sowie verspäteter Riemen- oder Injektorservice werden teuer.' }
      }
    },
    {
      id: 'bmw-n52', code: 'N52', aliases: ['N52B25', 'N52B30'], maker: 'BMW', regionKey: 'europe', years: '2004-2015',
      displacement: '2.5-3.0 L', layout: 'I6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['BMW 3 Series E90', '5 Series E60 / F10', 'X3', 'X5', 'Z4'], consumption: '8-13 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Naturally aspirated inline-six with magnesium-aluminium crankcase, aluminium head, Valvetronic, double VANOS, multipoint injection and timing chain.', issues: 'Electric water pump and thermostat; valve-cover and oil-filter housing leaks; Valvetronic eccentric-shaft sensor; DISA on some intakes; lifter noise on early versions.', pros: 'Smooth response, no turbo, efficient for an inline-six and strong enthusiast support.', cons: 'Cooling and Valvetronic parts are costly; exact power version and regional N51 emissions variant must be identified.' },
        es: { construction: 'Seis cilindros atmosférico con bloque magnesio-aluminio, culata de aluminio, Valvetronic, doble VANOS, inyección multipunto y cadena.', issues: 'Bomba eléctrica y termostato; fugas en tapa y filtro; sensor del eje Valvetronic; DISA en algunas admisiones; taqués tempranos.', pros: 'Respuesta suave, sin turbo, eficiente para seis cilindros y mucho soporte.', cons: 'Refrigeración y Valvetronic son caros; hay que identificar potencia exacta y variante N51 regional.' },
        fr: { construction: 'Six cylindres atmosphérique, carter magnésium-aluminium, culasse aluminium, Valvetronic, double VANOS, injection multipoint et chaîne.', issues: 'Pompe électrique et thermostat ; fuites couvre-culasse et filtre ; capteur arbre Valvetronic ; DISA selon admission ; poussoirs précoces.', pros: 'Réponse souple, sans turbo, efficace pour un six cylindres et bon support.', cons: 'Refroidissement et Valvetronic coûtent cher ; version de puissance et variante N51 régionale à identifier.' },
        de: { construction: 'Saug-Reihensechszylinder mit Magnesium-Aluminium-Kurbelgehäuse, Aluminiumkopf, Valvetronic, Doppel-VANOS, MPI und Steuerkette.', issues: 'Elektrische Wasserpumpe und Thermostat; Ventildeckel- und Ölfiltergehäuselecks; Valvetronic-Sensor; teils DISA; frühes Hydrostößelgeräusch.', pros: 'Sanfte Leistungsabgabe, kein Turbo, für einen Reihensechser effizient und guter Support.', cons: 'Kühlung und Valvetronic sind teuer; Leistungsstufe und regionale N51-Variante genau bestimmen.' }
      }
    },
    {
      id: 'vw-ea211', code: 'EA211', aliases: ['1.0 TSI', '1.2 TSI', '1.4 TSI', '1.5 TSI'], maker: 'Volkswagen Group', regionKey: 'europe', years: '2011-present',
      displacement: '1.0-1.6 L', layout: 'I3 / I4 · DOHC', fuelKey: 'petrol', aspirationKey: 'variantDependent',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingBelt',
      applications: ['VW Golf / Polo / T-Roc', 'Audi A1 / A3', 'Skoda Fabia / Octavia', 'SEAT Ibiza / Leon'], consumption: '4.5-8 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '200,000-350,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Modular small-engine family with aluminium block, belt-driven camshafts and naturally aspirated or turbocharged MPI/GDI versions depending on code.', issues: 'Water-pump and thermostat housing; turbo wastegate actuator on TSI; direct-injection deposits; oil or coolant leaks; belt inspection requirements.', pros: 'Light, efficient, widely used and supported by modern diagnostics and parts.', cons: 'EA211 covers many different engines; cylinder count, injection, cylinder deactivation and belt schedule vary by suffix.' },
        es: { construction: 'Familia modular pequeña con bloque de aluminio, árboles por correa y versiones atmosféricas o turbo MPI/GDI según código.', issues: 'Bomba y termostato; actuador wastegate en TSI; depósitos de inyección directa; fugas de aceite o refrigerante; revisión de correa.', pros: 'Ligero, eficiente, muy usado y con buen diagnóstico y piezas.', cons: 'EA211 incluye muchos motores; cilindros, inyección, desconexión y programa de correa cambian por sufijo.' },
        fr: { construction: 'Petite famille modulaire, bloc aluminium, arbres par courroie et versions atmosphériques ou turbo MPI/GDI selon code.', issues: 'Pompe et thermostat ; actuateur wastegate TSI ; dépôts injection directe ; fuites huile ou liquide ; contrôle de courroie.', pros: 'Léger, efficace, très répandu et bien couvert en diagnostic et pièces.', cons: 'EA211 regroupe beaucoup de moteurs ; cylindres, injection, désactivation et échéance courroie varient selon suffixe.' },
        de: { construction: 'Modulare Kleinmotorfamilie mit Aluminiumblock, zahnriemengetriebenen Nockenwellen und je Code Saug- oder Turbo-MPI/GDI-Versionen.', issues: 'Wasserpumpen- und Thermostatgehäuse; Wastegate-Steller beim TSI; Direkteinspritzerablagerungen; Öl- oder Kühlmittellecks; Riemenkontrolle.', pros: 'Leicht, effizient, weit verbreitet und gute Diagnose- sowie Teileversorgung.', cons: 'EA211 umfasst viele Motoren; Zylinderzahl, Einspritzung, Zylinderabschaltung und Riemenplan unterscheiden sich nach Suffix.' }
      }
    },
    {
      id: 'mercedes-om651', code: 'OM651', aliases: ['OM651 DE22', 'CDI 2.1', 'BlueTEC 2.1'], maker: 'Mercedes-Benz', regionKey: 'europe', years: '2008-2020',
      displacement: '1.8-2.1 L', layout: 'I4 · DOHC · 16V', fuelKey: 'diesel', aspirationKey: 'turbocharged',
      injectionKey: 'commonRail', blockKey: 'castIronBlock', timingKey: 'timingChain',
      applications: ['Mercedes C-Class', 'E-Class', 'GLK / GLC', 'Sprinter', 'Vito'], consumption: '5-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-500,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Common-rail four-cylinder diesel with iron block, aluminium head, rear-mounted timing chain and single or multi-stage turbocharging by version.', issues: 'Early piezo injector campaigns; rear timing-chain wear; EGR, DPF and intake deposits; water pump and cooling leaks; oil leaks and turbo controls.', pros: 'Strong efficiency, broad model coverage, good torque and high-mileage potential after updates.', cons: 'Rear chain access is labour-intensive; emissions system and injector generation must be identified before repair.' },
        es: { construction: 'Diésel cuatro cilindros common rail con bloque de hierro, culata de aluminio, cadena trasera y uno o varios turbos según versión.', issues: 'Campañas de inyectores piezo; desgaste de cadena trasera; EGR, DPF y admisión; bomba y fugas; aceite y control de turbo.', pros: 'Muy eficiente, usado en muchos modelos, buen par y alto kilometraje tras actualizaciones.', cons: 'Acceder a la cadena es costoso; hay que identificar emisiones y generación de inyectores.' },
        fr: { construction: 'Diesel quatre cylindres common rail, bloc fonte, culasse aluminium, chaîne arrière et suralimentation simple ou étagée selon version.', issues: 'Campagnes injecteurs piézo ; usure chaîne arrière ; EGR, DPF et admission ; pompe et fuites ; huile et commande turbo.', pros: 'Très efficient, large diffusion, bon couple et fort kilométrage après mises à jour.', cons: 'Accès chaîne très coûteux ; génération dépollution et injecteurs à identifier avant réparation.' },
        de: { construction: 'Common-Rail-Vierzylinder-Diesel mit Graugussblock, Aluminiumkopf, hinten liegender Steuerkette und je Version ein- oder mehrstufiger Aufladung.', issues: 'Frühe Piezo-Injektoraktionen; hinterer Kettenverschleiß; EGR, DPF und Ansaugung; Wasserpumpe und Lecks; Öl und Turbosteuerung.', pros: 'Sehr effizient, breit eingesetzt, gutes Drehmoment und hohe Laufleistung nach Aktualisierungen.', cons: 'Kettenzugang ist arbeitsintensiv; Abgassystem- und Injektorgeneration vor Reparatur bestimmen.' }
      }
    },
    {
      id: 'toyota-2zr-fe', code: '2ZR-FE', aliases: ['2ZR', '2ZR-FAE'], maker: 'Toyota', regionKey: 'japan', years: '2006-present',
      displacement: '1.8 L · 1,798 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Toyota Corolla / Auris', 'Avensis', 'C-HR', 'Lotus Elise variants'], consumption: '6-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-450,000 km', oilRecord: 'toyota-corolla-2zr', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 1.8-litre four-cylinder with DOHC 16-valve head, dual VVT-i, multipoint injection and timing chain; Valvematic is used on related 2ZR-FAE versions.', issues: 'Water-pump leakage; timing-cover and valve-cover seepage; oil consumption with age; Valvematic actuator on FAE; cooling neglect.', pros: 'Efficient, globally common, durable and supported by affordable service parts.', cons: 'FE, FAE and hybrid FXE versions are not interchangeable descriptions; exact suffix and oil specification matter.' },
        es: { construction: 'Cuatro cilindros 1.8 de aluminio, DOHC 16 válvulas, doble VVT-i, inyección multipunto y cadena; versiones 2ZR-FAE usan Valvematic.', issues: 'Fuga de bomba de agua; sudoración en tapa y distribución; consumo con edad; actuador Valvematic en FAE; refrigeración descuidada.', pros: 'Eficiente, mundial, duradero y con repuestos asequibles.', cons: 'FE, FAE e híbrido FXE no son la misma descripción; importan sufijo y aceite exactos.' },
        fr: { construction: 'Quatre cylindres aluminium 1,8 litre, DOHC 16 soupapes, double VVT-i, injection multipoint et chaîne ; Valvematic sur 2ZR-FAE associé.', issues: 'Fuite pompe à eau ; suintements carter et couvre-culasse ; consommation avec âge ; actuateur Valvematic FAE ; refroidissement négligé.', pros: 'Efficace, mondialement répandu, durable et pièces abordables.', cons: 'FE, FAE et hybride FXE ne sont pas identiques ; suffixe et huile exacte comptent.' },
        de: { construction: '1,8-Liter-Aluminium-Vierzylinder mit DOHC-16V, Doppel-VVT-i, MPI und Kette; verwandte 2ZR-FAE nutzen Valvematic.', issues: 'Wasserpumpenleck; Steuergehäuse- und Ventildeckelschwitzen; Ölverbrauch im Alter; Valvematic-Steller beim FAE; Kühlungsvernachlässigung.', pros: 'Effizient, weltweit verbreitet, haltbar und günstige Serviceteile.', cons: 'FE, FAE und Hybrid-FXE sind nicht gleich; genaues Suffix und Ölvorgabe zählen.' }
      }
    },
    {
      id: 'toyota-2gr-fe', code: '2GR-FE', aliases: ['2GR', '2GR-FKS'], maker: 'Toyota / Lexus', regionKey: 'japan', years: '2004-present',
      displacement: '3.5 L · 3,456 cc', layout: 'V6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Toyota Camry / Highlander / Sienna', 'Lexus ES / RX / IS', 'Lotus Evora'], consumption: '8-14 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-500,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 3.5-litre V6 family with DOHC heads, variable timing and timing chains; injection changed from port to combined or direct systems on later suffixes.', issues: 'Early external VVT-i oil hose; water pump with significant labour on some vehicles; timing-cover oil leaks; ignition coils; cooling-system neglect.', pros: 'Strong performance, smooth operation, broad Toyota/Lexus use and high-mileage capability.', cons: 'Transverse installation makes some repairs expensive; FE, FSE and FKS injection systems require exact identification.' },
        es: { construction: 'Familia V6 3.5 de aluminio, culatas DOHC, distribución variable y cadenas; la inyección cambia en sufijos posteriores.', issues: 'Tubo externo VVT-i temprano; bomba de agua laboriosa; fugas de tapa de distribución; bobinas; refrigeración descuidada.', pros: 'Buen rendimiento, suavidad, uso amplio Toyota/Lexus y alto kilometraje.', cons: 'Montaje transversal encarece reparaciones; FE, FSE y FKS requieren identificación exacta.' },
        fr: { construction: 'Famille V6 aluminium 3,5 litres, culasses DOHC, calage variable et chaînes ; injection différente sur suffixes récents.', issues: 'Durite externe VVT-i précoce ; pompe à eau coûteuse en main-d’œuvre ; fuites carter distribution ; bobines ; refroidissement négligé.', pros: 'Bonnes performances, souplesse, large usage Toyota/Lexus et fort kilométrage.', cons: 'Montage transversal rend certaines réparations chères ; FE, FSE et FKS à identifier exactement.' },
        de: { construction: '3,5-Liter-Aluminium-V6-Familie mit DOHC-Köpfen, variablen Steuerzeiten und Ketten; spätere Suffixe mit anderer Einspritzung.', issues: 'Frühe externe VVT-i-Ölleitung; arbeitsintensive Wasserpumpe; Steuergehäuse-Öllecks; Zündspulen; vernachlässigte Kühlung.', pros: 'Starke Leistung, Laufruhe, breite Toyota/Lexus-Nutzung und hohe Laufleistung.', cons: 'Quereinbau verteuert manche Reparaturen; FE, FSE und FKS genau unterscheiden.' }
      }
    },
    {
      id: 'honda-r18a', code: 'R18A / R18Z', aliases: ['R18A1', 'R18A2', 'R18Z1'], maker: 'Honda', regionKey: 'japan', years: '2005-2021',
      displacement: '1.8 L · 1,799 cc', layout: 'I4 · SOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Honda Civic', 'Stream', 'HR-V / Vezel variants'], consumption: '6-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '300,000-450,000 km', oilRecord: 'honda-civic-r18', statusKey: 'starterReview',
      text: {
        en: { construction: 'Aluminium 1.8-litre SOHC 16-valve four-cylinder with i-VTEC economy strategy, multipoint injection and timing chain.', issues: 'Valve-clearance neglect; engine mounts; valve-cover and oil leaks; cooling-system age; starter and ignition components.', pros: 'Simple, economical, durable and easy to service in common Civic applications.', cons: 'Valve adjustment is often ignored; vibration may come from mounts rather than internal engine damage.' },
        es: { construction: 'Cuatro cilindros 1.8 de aluminio, SOHC 16 válvulas, estrategia i-VTEC, inyección multipunto y cadena.', issues: 'Holgura de válvulas olvidada; soportes; fugas de tapa y aceite; refrigeración por edad; arranque y encendido.', pros: 'Sencillo, económico, duradero y fácil de mantener en Civic.', cons: 'Se ignora el ajuste de válvulas; vibraciones pueden venir de soportes y no del motor interno.' },
        fr: { construction: 'Quatre cylindres aluminium 1,8 litre SOHC 16 soupapes, stratégie i-VTEC économie, injection multipoint et chaîne.', issues: 'Jeu aux soupapes négligé ; supports ; fuites couvre-culasse et huile ; refroidissement âgé ; démarreur et allumage.', pros: 'Simple, économique, durable et facile à entretenir sur Civic.', cons: 'Réglage soupapes souvent oublié ; vibrations parfois dues aux supports et non au moteur.' },
        de: { construction: '1,8-Liter-Aluminium-Vierzylinder mit SOHC-16V, i-VTEC-Sparstrategie, MPI und Steuerkette.', issues: 'Vernachlässigtes Ventilspiel; Motorlager; Ventildeckel- und Öllecks; gealterte Kühlung; Starter und Zündung.', pros: 'Einfach, sparsam, haltbar und im Civic leicht zu warten.', cons: 'Ventileinstellung wird oft vergessen; Vibrationen kommen häufig von Lagern statt innerem Motorschaden.' }
      }
    },
    {
      id: 'subaru-fb20', code: 'FB20', aliases: ['FB20B', 'FB20D'], maker: 'Subaru', regionKey: 'japan', years: '2010-present',
      displacement: '2.0 L · 1,995 cc', layout: 'Flat-4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Subaru Impreza', 'XV / Crosstrek', 'Forester', 'Legacy variants'], consumption: '7-10 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 2.0-litre horizontally opposed four-cylinder with DOHC heads, timing chains and port or direct injection depending on version.', issues: 'Oil consumption on some early engines; timing-cover and cam-carrier leaks; cooling-system maintenance; intake deposits on direct-injection FB20D.', pros: 'Low centre of gravity, good efficiency, smooth operation and timing chains instead of the older EJ belt.', cons: 'Boxer access raises labour time; oil level must be monitored and FB20B and FB20D should not be confused.' },
        es: { construction: 'Bóxer 2.0 de aluminio, culatas DOHC, cadenas e inyección indirecta o directa según versión.', issues: 'Consumo de aceite en algunos tempranos; fugas de tapa y portalevas; refrigeración; depósitos en FB20D directo.', pros: 'Centro de gravedad bajo, eficiencia, suavidad y cadenas frente a la correa EJ.', cons: 'Acceso bóxer aumenta mano de obra; vigila aceite y no confundas FB20B con FB20D.' },
        fr: { construction: 'Boxer aluminium 2,0 litres, culasses DOHC, chaînes et injection indirecte ou directe selon version.', issues: 'Consommation d’huile sur certains premiers moteurs ; fuites carter et porte-arbres ; refroidissement ; dépôts sur FB20D direct.', pros: 'Centre de gravité bas, efficacité, souplesse et chaînes plutôt que courroie EJ.', cons: 'Accès boxer augmente la main-d’œuvre ; surveiller huile et distinguer FB20B de FB20D.' },
        de: { construction: '2,0-Liter-Aluminium-Boxer mit DOHC-Köpfen, Ketten und je Version Saugrohr- oder Direkteinspritzung.', issues: 'Ölverbrauch bei manchen frühen Motoren; Steuerdeckel- und Nockenwellenträgerlecks; Kühlung; Ablagerungen beim Direkteinspritzer FB20D.', pros: 'Niedriger Schwerpunkt, Effizienz, Laufruhe und Ketten statt älterem EJ-Riemen.', cons: 'Boxerzugang erhöht Arbeitszeit; Ölstand überwachen und FB20B von FB20D unterscheiden.' }
      }
    },
    {
      id: 'mitsubishi-4b11', code: '4B11', aliases: ['4B11T', '2.0 MIVEC'], maker: 'Mitsubishi', regionKey: 'japan', years: '2007-present',
      displacement: '2.0 L · 1,998 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'variantDependent',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Mitsubishi Lancer', 'Outlander', 'ASX / RVR', 'Lancer Evolution X'], consumption: '7-14 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 2.0-litre DOHC MIVEC four-cylinder with timing chain; naturally aspirated and high-output turbo 4B11T versions have major hardware differences.', issues: 'Chain noise with poor oil service; valve-clearance neglect; oil consumption or leaks; cooling; turbo heat, tuning and detonation on 4B11T.', pros: 'Modern layout, good parts availability, strong naturally aspirated service life and major performance potential in turbo form.', cons: 'Do not transfer Evolution advice to standard engines; turbo cars are highly sensitive to tuning and maintenance history.' },
        es: { construction: 'Cuatro cilindros 2.0 de aluminio, DOHC MIVEC y cadena; atmosféricos y turbo 4B11T tienen grandes diferencias.', issues: 'Ruido de cadena con mal aceite; holgura de válvulas; consumo o fugas; refrigeración; calor, tuning y detonación en 4B11T.', pros: 'Diseño moderno, piezas disponibles, buena vida en atmosféricos y gran potencial turbo.', cons: 'No apliques consejos Evolution al motor normal; turbo depende mucho de tuning e historial.' },
        fr: { construction: 'Quatre cylindres aluminium 2,0 litres DOHC MIVEC et chaîne ; versions atmosphériques et turbo 4B11T très différentes.', issues: 'Bruit chaîne avec mauvais entretien ; jeu soupapes ; consommation ou fuites ; refroidissement ; chaleur, tuning et cliquetis sur 4B11T.', pros: 'Architecture moderne, pièces disponibles, bonne durée atmosphérique et fort potentiel turbo.', cons: 'Ne pas appliquer les conseils Evolution au moteur standard ; turbo très sensible au tuning et à l’historique.' },
        de: { construction: '2,0-Liter-Aluminium-DOHC-MIVEC-Vierzylinder mit Kette; Saug- und Hochleistungs-Turbo-4B11T unterscheiden sich stark.', issues: 'Kettengeräusch bei schlechtem Ölservice; Ventilspiel; Ölverbrauch oder Lecks; Kühlung; Hitze, Tuning und Klopfen beim 4B11T.', pros: 'Moderner Aufbau, gute Teilelage, lange Saugerlaufzeit und großes Turbopotenzial.', cons: 'Evolution-Ratschläge nicht auf Standardmotoren übertragen; Turbos sind stark von Tuning und Historie abhängig.' }
      }
    },
    {
      id: 'hyundai-g4na', code: 'G4NA', aliases: ['Nu 2.0 MPI', 'Nu 2.0 GDI'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2010-present',
      displacement: '2.0 L · 1,999 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Elantra / Sonata / Tucson', 'Kia Sportage / Optima / Soul'], consumption: '7-11 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '180,000-320,000 km', oilRecord: '', statusKey: 'recallCheck',
      text: {
        en: { construction: 'Nu-family aluminium 2.0-litre four-cylinder with DOHC head, dual CVVT, timing chain and MPI or GDI depending on market and suffix.', issues: 'Cylinder scuffing and oil-consumption reports in some markets; catalyst debris concerns; chain noise; cooling and oil leaks; recall coverage varies by VIN.', pros: 'Simple naturally aspirated output, wide parts supply and good everyday economy in healthy examples.', cons: 'Condition and campaigns vary strongly by market; compression, cylinder noise, oil level and VIN history require attention.' },
        es: { construction: 'Motor Nu 2.0 de aluminio, DOHC, doble CVVT, cadena y MPI o GDI según mercado y sufijo.', issues: 'Rayado de cilindros y consumo en algunos mercados; residuos de catalizador; ruido de cadena; refrigeración y fugas; campañas por VIN.', pros: 'Potencia atmosférica sencilla, muchas piezas y buen consumo diario si está sano.', cons: 'Estado y campañas cambian por mercado; revisa compresión, ruido, aceite e historial VIN.' },
        fr: { construction: 'Moteur Nu aluminium 2,0 litres, DOHC, double CVVT, chaîne et MPI ou GDI selon marché et suffixe.', issues: 'Rayures cylindres et consommation selon marchés ; débris catalyseur ; bruit chaîne ; refroidissement et fuites ; campagnes par VIN.', pros: 'Puissance atmosphérique simple, pièces nombreuses et bonne économie au quotidien en bon état.', cons: 'État et campagnes varient selon marché ; contrôler compression, bruit, huile et historique VIN.' },
        de: { construction: 'Nu-2,0-Liter-Aluminium-Vierzylinder mit DOHC, Doppel-CVVT, Kette und je Markt MPI oder GDI.', issues: 'Zylinderriefen- und Ölverbrauchsmeldungen je Markt; Katalysatorpartikel; Kettengeräusch; Kühlung und Lecks; Aktionen je VIN.', pros: 'Einfache Saugerleistung, gute Teilelage und ordentlicher Alltagsverbrauch bei gesundem Motor.', cons: 'Zustand und Aktionen unterscheiden sich stark; Kompression, Geräusch, Ölstand und VIN-Historie prüfen.' }
      }
    },
    {
      id: 'hyundai-g4fj', code: 'G4FJ', aliases: ['1.6 T-GDI', 'Gamma Turbo'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2011-2021',
      displacement: '1.6 L · 1,591 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'turbocharged',
      injectionKey: 'directInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Veloster / i30 / Tucson', 'Kia Ceed GT / Soul / Sportage'], consumption: '7-11 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '180,000-300,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Gamma-family 1.6-litre turbocharged direct-injection engine with aluminium construction, dual CVVT and timing chain.', issues: 'Intake-valve carbon deposits; LSPI or detonation with wrong oil or fuel; turbo oil and cooling lines; chain noise; ignition and high-pressure fuel system.', pros: 'Strong performance from small displacement, broad tuning knowledge and good efficiency when driven moderately.', cons: 'Sensitive to oil quality, fuel and tuning; heat and short-trip deposits increase maintenance demands.' },
        es: { construction: 'Motor Gamma 1.6 turbo de inyección directa, aluminio, doble CVVT y cadena.', issues: 'Carbón en admisión; LSPI o detonación con aceite o combustible incorrecto; líneas de turbo; cadena; encendido y alta presión.', pros: 'Buen rendimiento con poca cilindrada, mucho conocimiento de tuning y eficiencia con uso moderado.', cons: 'Sensible a aceite, combustible y preparación; calor y trayectos cortos aumentan mantenimiento.' },
        fr: { construction: 'Moteur Gamma 1,6 litre turbo à injection directe, aluminium, double CVVT et chaîne.', issues: 'Calamine admission ; LSPI ou cliquetis avec mauvaise huile ou carburant ; conduites turbo ; chaîne ; allumage et haute pression.', pros: 'Fortes performances avec petite cylindrée, tuning bien connu et bonne efficacité en conduite modérée.', cons: 'Sensible à l’huile, au carburant et au tuning ; chaleur et petits trajets augmentent l’entretien.' },
        de: { construction: 'Gamma-1,6-Liter-Turbo-Direkteinspritzer in Aluminiumbauweise mit Doppel-CVVT und Steuerkette.', issues: 'Einlassverkokung; LSPI oder Klopfen bei falschem Öl/Kraftstoff; Turboöl- und Kühlleitungen; Kette; Zündung und Hochdrucksystem.', pros: 'Starke Leistung aus kleinem Hubraum, gute Tuningkenntnis und Effizienz bei moderater Fahrweise.', cons: 'Empfindlich auf Öl, Kraftstoff und Tuning; Hitze und Kurzstrecke erhöhen Wartungsbedarf.' }
      }
    },
    {
      id: 'hyundai-g4ke', code: 'G4KE', aliases: ['Theta II 2.4 MPI'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2007-2020',
      displacement: '2.4 L · 2,359 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Sonata / Santa Fe', 'Kia Optima / Sorento / Sportage'], consumption: '8-12 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '150,000-300,000 km', oilRecord: '', statusKey: 'recallCheck',
      text: {
        en: { construction: 'Theta II 2.4-litre naturally aspirated aluminium four-cylinder with DOHC head, dual CVVT, multipoint injection and timing chain.', issues: 'Rod-bearing failure or seizure reports; cylinder scuffing and oil use; chain noise; catalyst concerns; recalls and warranty extensions vary by market and VIN.', pros: 'Good low-speed torque, simple MPI equipment and broad parts availability.', cons: 'Failure history requires careful VIN campaign check, cold-noise inspection, oil-pressure evidence and compression testing.' },
        es: { construction: 'Theta II 2.4 atmosférico de aluminio, DOHC, doble CVVT, inyección multipunto y cadena.', issues: 'Fallos de cojinetes o gripado; rayado y consumo; cadena; catalizador; campañas y garantías según mercado y VIN.', pros: 'Buen par, equipo MPI sencillo y muchas piezas.', cons: 'El historial exige revisar campañas VIN, ruido en frío, presión de aceite y compresión.' },
        fr: { construction: 'Theta II 2,4 litres atmosphérique aluminium, DOHC, double CVVT, injection multipoint et chaîne.', issues: 'Coussinets ou serrage ; rayures et consommation ; chaîne ; catalyseur ; rappels et garanties selon marché et VIN.', pros: 'Bon couple, équipement MPI simple et pièces nombreuses.', cons: 'Historique exige contrôle campagnes VIN, bruit à froid, pression d’huile et compression.' },
        de: { construction: 'Theta-II-2,4-Liter-Aluminium-Saugmotor mit DOHC, Doppel-CVVT, MPI und Steuerkette.', issues: 'Pleuellagerausfall oder Fresser; Zylinderriefen und Ölverbrauch; Kette; Katalysator; Rückrufe und Garantie je Markt/VIN.', pros: 'Gutes Drehmoment, einfache MPI-Technik und breite Teileversorgung.', cons: 'Historie verlangt VIN-Aktionsprüfung, Kaltgeräusch, Öldrucknachweis und Kompressionstest.' }
      }
    },
    {
      id: 'hyundai-d4fb', code: 'D4FB', aliases: ['1.6 CRDi', 'U 1.6 diesel'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2005-present',
      displacement: '1.6 L · 1,582 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'diesel', aspirationKey: 'turbocharged',
      injectionKey: 'commonRail', blockKey: 'castIronBlock', timingKey: 'timingChain',
      applications: ['Hyundai i20 / i30 / Elantra', 'Kia Rio / Ceed / Soul'], consumption: '4.5-7 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'U-family 1.6-litre common-rail turbodiesel with iron block, aluminium head, timing chain and emissions equipment that evolved by generation.', issues: 'Injector wear and correction; EGR and intake deposits; DPF loading; turbo oil supply; chain noise; glow system and boost leaks.', pros: 'Very good fuel economy, useful torque and wide European compact-car coverage.', cons: 'Short trips are hard on DPF/EGR; injector and turbo repairs can exceed the value of older cars.' },
        es: { construction: 'Diésel U 1.6 common rail con bloque de hierro, culata de aluminio, cadena y emisiones según generación.', issues: 'Inyectores y correcciones; EGR y admisión; DPF; aceite del turbo; cadena; calentadores y fugas de presión.', pros: 'Muy buen consumo, par útil y uso amplio en compactos europeos.', cons: 'Trayectos cortos dañan DPF/EGR; inyectores y turbo pueden superar el valor de coches viejos.' },
        fr: { construction: 'Diesel U 1,6 litre common rail, bloc fonte, culasse aluminium, chaîne et dépollution évolutive.', issues: 'Injecteurs et corrections ; EGR et admission ; DPF ; huile turbo ; chaîne ; préchauffage et fuites de pression.', pros: 'Très bonne sobriété, couple utile et large diffusion sur compactes européennes.', cons: 'Petits trajets difficiles pour DPF/EGR ; injecteurs et turbo peuvent dépasser la valeur des anciennes voitures.' },
        de: { construction: 'U-1,6-Liter-Common-Rail-Turbodiesel mit Graugussblock, Aluminiumkopf, Kette und generationsabhängiger Abgastechnik.', issues: 'Injektorverschleiß und Korrektur; EGR und Ansaugung; DPF; Turboölversorgung; Kette; Glühsystem und Ladedrucklecks.', pros: 'Sehr sparsamer Verbrauch, brauchbares Drehmoment und breite Nutzung in europäischen Kompaktwagen.', cons: 'Kurzstrecke belastet DPF/EGR; Injektor- und Turboreparaturen können den Fahrzeugwert übersteigen.' }
      }
    },
    {
      id: 'hyundai-d4hb', code: 'D4HB', aliases: ['R 2.2 CRDi', '2.2 CRDi'], maker: 'Hyundai / Kia', regionKey: 'korea', years: '2009-present',
      displacement: '2.2 L · 2,199 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'diesel', aspirationKey: 'turbocharged',
      injectionKey: 'commonRail', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Hyundai Santa Fe / Palisade', 'Kia Sorento / Carnival'], consumption: '6-9 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-450,000 km', oilRecord: '', statusKey: 'starterReview',
      text: {
        en: { construction: 'R-series 2.2-litre common-rail turbodiesel with light-alloy construction, variable-geometry turbo, timing chain and market-dependent DPF/SCR equipment.', issues: 'DPF and EGR loading; intake deposits; injector correction; chain noise; turbo controls; cooling leaks and SCR/AdBlue faults on later versions.', pros: 'Strong SUV torque, good towing ability and efficient long-distance operation.', cons: 'Complex emissions equipment raises repair cost; exact market and generation determine DPF, SCR and oil requirements.' },
        es: { construction: 'Diésel R 2.2 common rail de aleación ligera, turbo variable, cadena y DPF/SCR según mercado.', issues: 'Carga DPF/EGR; admisión; corrección de inyectores; cadena; control de turbo; fugas y SCR/AdBlue posterior.', pros: 'Mucho par para SUV, buen remolque y eficiencia en carretera.', cons: 'Emisiones complejas elevan costes; mercado y generación determinan DPF, SCR y aceite.' },
        fr: { construction: 'Diesel R 2,2 litres common rail en alliage léger, turbo variable, chaîne et DPF/SCR selon marché.', issues: 'Charge DPF/EGR ; admission ; corrections injecteurs ; chaîne ; commande turbo ; fuites et SCR/AdBlue récent.', pros: 'Fort couple SUV, bonne capacité de remorquage et efficacité routière.', cons: 'Dépollution complexe coûteuse ; marché et génération déterminent DPF, SCR et huile.' },
        de: { construction: 'R-2,2-Liter-Common-Rail-Turbodiesel in Leichtmetallbauweise mit VTG-Lader, Kette und marktabhängigem DPF/SCR.', issues: 'DPF/EGR-Beladung; Ansaugung; Injektorkorrektur; Kette; Turbosteuerung; Kühllecks und spätere SCR/AdBlue-Fehler.', pros: 'Starkes SUV-Drehmoment, gute Zugfähigkeit und effizient auf Langstrecke.', cons: 'Komplexe Abgastechnik erhöht Kosten; Markt und Generation bestimmen DPF, SCR und Ölvorgaben.' }
      }
    },
    {
      id: 'gm-l83', code: 'L83 5.3 EcoTec3', aliases: ['L83', '5.3 EcoTec3'], maker: 'General Motors', regionKey: 'usa', years: '2014-2019',
      displacement: '5.3 L · 5,328 cc', layout: 'V8 · OHV · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'directInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Chevrolet Silverado / Tahoe / Suburban', 'GMC Sierra / Yukon'], consumption: '12-18 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Gen V 5.3-litre aluminium pushrod V8 with direct injection, variable cam timing, Active Fuel Management and timing chain.', issues: 'AFM lifter and cam wear; oil consumption; direct-injection injectors and high-pressure pump; vacuum pump; thermostat and cooling leaks.', pros: 'Strong truck torque, compact V8 packaging, large North American parts supply and good highway durability.', cons: 'AFM and direct injection add complexity compared with LM7; service history and oil-change quality strongly affect lifters.' },
        es: { construction: 'V8 Gen V 5.3 de aluminio, varillas, inyección directa, árbol variable, AFM y cadena.', issues: 'Taqués AFM y levas; consumo; inyectores y bomba de alta; bomba de vacío; termostato y fugas.', pros: 'Mucho par, V8 compacto, enorme oferta de piezas y buena duración en carretera.', cons: 'AFM e inyección directa añaden complejidad frente a LM7; historial y aceite afectan mucho a taqués.' },
        fr: { construction: 'V8 Gen V aluminium 5,3 litres à tiges, injection directe, calage variable, AFM et chaîne.', issues: 'Poussoirs AFM et cames ; consommation ; injecteurs et pompe haute pression ; pompe à vide ; thermostat et fuites.', pros: 'Fort couple, V8 compact, pièces très nombreuses et bonne endurance routière.', cons: 'AFM et injection directe ajoutent de la complexité face au LM7 ; entretien d’huile crucial pour les poussoirs.' },
        de: { construction: 'Gen-V-5,3-Liter-Aluminium-Stößelstangen-V8 mit Direkteinspritzung, variabler Nockensteuerung, AFM und Kette.', issues: 'AFM-Stößel und Nocken; Ölverbrauch; DI-Injektoren und Hochdruckpumpe; Vakuumpumpe; Thermostat und Lecks.', pros: 'Starkes Truck-Drehmoment, kompakter V8, riesige Teileversorgung und gute Langstreckenhaltbarkeit.', cons: 'AFM und DI sind komplexer als beim LM7; Historie und Ölwechselqualität beeinflussen Stößel stark.' }
      }
    },
    {
      id: 'gm-lfx', code: 'LFX 3.6', aliases: ['3.6 HFV6', 'LFX V6'], maker: 'General Motors', regionKey: 'usa', years: '2012-2020',
      displacement: '3.6 L · 3,564 cc', layout: 'V6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'directInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Chevrolet Camaro / Impala / Traverse', 'Cadillac ATS / CTS / SRX', 'Buick LaCrosse'], consumption: '9-14 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'High Feature 3.6-litre aluminium DOHC V6 with direct injection, variable timing and multiple timing chains.', issues: 'Chain wear when oil service is extended; PCV restriction and oil use; water pump; thermostat; intake deposits and high-pressure fuel components.', pros: 'Good power without turbocharging, broad GM application and improved design over some earlier HFV6 versions.', cons: 'Chain system is complex and oil-sensitive; transverse applications can make cooling and timing work expensive.' },
        es: { construction: 'V6 High Feature 3.6 de aluminio, DOHC, inyección directa, distribución variable y varias cadenas.', issues: 'Desgaste de cadenas con aceite prolongado; PCV y consumo; bomba; termostato; depósitos y alta presión.', pros: 'Buena potencia sin turbo, uso amplio GM y mejoras frente a HFV6 anteriores.', cons: 'Cadenas complejas y sensibles al aceite; montaje transversal encarece refrigeración y distribución.' },
        fr: { construction: 'V6 High Feature aluminium 3,6 litres DOHC, injection directe, calage variable et plusieurs chaînes.', issues: 'Usure chaînes avec intervalles longs ; PCV et consommation ; pompe ; thermostat ; dépôts et haute pression.', pros: 'Bonne puissance sans turbo, large usage GM et améliorations face aux anciens HFV6.', cons: 'Distribution complexe et sensible à l’huile ; montage transversal rend refroidissement et chaînes coûteux.' },
        de: { construction: 'High-Feature-3,6-Liter-Aluminium-DOHC-V6 mit Direkteinspritzung, variablen Steuerzeiten und mehreren Ketten.', issues: 'Kettenverschleiß bei langen Ölintervallen; PCV und Ölverbrauch; Wasserpumpe; Thermostat; Ablagerungen und Hochdrucksystem.', pros: 'Gute Leistung ohne Turbo, breite GM-Nutzung und Verbesserungen gegenüber älteren HFV6.', cons: 'Komplexes, ölempfindliches Kettensystem; Quereinbau verteuert Kühl- und Steuerarbeiten.' }
      }
    },
    {
      id: 'ford-23-ecoboost', code: '2.3 EcoBoost', aliases: ['EcoBoost 2.3', '2.3L EcoBoost'], maker: 'Ford', regionKey: 'usa', years: '2015-present',
      displacement: '2.3 L · 2,261 cc', layout: 'I4 · DOHC · 16V', fuelKey: 'petrol', aspirationKey: 'turbocharged',
      injectionKey: 'directInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Ford Mustang', 'Focus RS', 'Ranger', 'Explorer', 'Bronco'], consumption: '8-13 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '200,000-350,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 2.3-litre turbocharged direct-injection four-cylinder with DOHC head, variable timing and timing chain; calibration and hardware vary widely by model.', issues: 'Cooling and head-gasket history on specific early applications; intake deposits; turbo and oil lines; high-pressure fuel system; overheating and tuning damage.', pros: 'Strong torque and power, broad truck and performance use, good diagnostic and aftermarket support.', cons: 'Mustang, Ranger, Focus RS and Explorer versions are not identical; modified calibrations can greatly change reliability.' },
        es: { construction: 'Cuatro cilindros 2.3 turbo de aluminio, inyección directa, DOHC, distribución variable y cadena; cambia mucho por modelo.', issues: 'Refrigeración y junta en aplicaciones tempranas concretas; depósitos; turbo y aceite; alta presión; sobrecalentamiento y tuning.', pros: 'Mucho par y potencia, uso en pickups y deportivos, buen diagnóstico y aftermarket.', cons: 'Mustang, Ranger, Focus RS y Explorer no son iguales; calibraciones modificadas cambian fiabilidad.' },
        fr: { construction: 'Quatre cylindres aluminium 2,3 litres turbo à injection directe, DOHC, calage variable et chaîne ; matériel variable selon modèle.', issues: 'Refroidissement et joint sur certaines applications précoces ; dépôts ; turbo et huile ; haute pression ; surchauffe et tuning.', pros: 'Fort couple et puissance, usage utilitaire et sportif, bon diagnostic et aftermarket.', cons: 'Mustang, Ranger, Focus RS et Explorer diffèrent ; calibrations modifiées changent fortement la fiabilité.' },
        de: { construction: '2,3-Liter-Aluminium-Turbo-Direkteinspritzer mit DOHC, variablen Steuerzeiten und Kette; Hardware je Modell sehr unterschiedlich.', issues: 'Kühlung und Kopfdichtung bestimmter früher Anwendungen; Ablagerungen; Turbo- und Ölleitungen; Hochdrucksystem; Überhitzung und Tuning.', pros: 'Starkes Drehmoment und Leistung, breite Truck- und Performance-Nutzung, gute Diagnose und Zubehör.', cons: 'Mustang, Ranger, Focus RS und Explorer sind nicht identisch; geänderte Kalibrierung beeinflusst Zuverlässigkeit stark.' }
      }
    },
    {
      id: 'ford-35-ecoboost', code: '3.5 EcoBoost', aliases: ['EcoBoost 3.5', '3.5L Twin Turbo'], maker: 'Ford', regionKey: 'usa', years: '2009-present',
      displacement: '3.5 L · 3,496 cc', layout: 'V6 · DOHC · 24V', fuelKey: 'petrol', aspirationKey: 'turbocharged',
      injectionKey: 'variantInjection', blockKey: 'aluminumLiners', timingKey: 'timingChain',
      applications: ['Ford F-150 / Expedition', 'Explorer', 'Transit', 'Lincoln Navigator'], consumption: '11-17 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Aluminium 3.5-litre twin-turbo V6 with DOHC heads, variable timing, timing chains and direct or dual injection depending on generation.', issues: 'Timing-chain stretch and cam phasers on some generations; internal water pump on transverse versions; turbo coolant/oil lines; intake deposits; ignition.', pros: 'High towing torque, strong performance and wide truck/SUV use.', cons: 'Longitudinal and transverse versions differ greatly; chain, water-pump and turbo repairs can be labour-intensive.' },
        es: { construction: 'V6 3.5 biturbo de aluminio, DOHC, distribución variable, cadenas e inyección directa o dual según generación.', issues: 'Cadena y variadores en algunas generaciones; bomba interna en transversales; líneas de turbo; depósitos; encendido.', pros: 'Mucho par de remolque, gran rendimiento y uso amplio en pickups/SUV.', cons: 'Longitudinal y transversal cambian mucho; cadena, bomba y turbos requieren mucha mano de obra.' },
        fr: { construction: 'V6 aluminium 3,5 litres biturbo, DOHC, calage variable, chaînes et injection directe ou double selon génération.', issues: 'Chaînes et déphaseurs selon générations ; pompe interne sur versions transversales ; conduites turbo ; dépôts ; allumage.', pros: 'Fort couple de remorquage, grandes performances et large usage utilitaire/SUV.', cons: 'Versions longitudinales et transversales très différentes ; chaînes, pompe et turbos coûteux en main-d’œuvre.' },
        de: { construction: '3,5-Liter-Aluminium-Biturbo-V6 mit DOHC, variablen Steuerzeiten, Ketten und je Generation Direkt- oder Doppeleinspritzung.', issues: 'Kettenlängung und Nockensteller mancher Generationen; interne Wasserpumpe bei Quereinbau; Turboleitungen; Ablagerungen; Zündung.', pros: 'Hohes Zugdrehmoment, starke Leistung und breite Truck/SUV-Nutzung.', cons: 'Längs- und Querversionen unterscheiden sich stark; Kette, Pumpe und Turbos sind arbeitsintensiv.' }
      }
    },
    {
      id: 'chrysler-hemi-57', code: '5.7 HEMI', aliases: ['5.7 Eagle', 'Hemi 5.7', 'EZB'], maker: 'Chrysler / Dodge / Ram', regionKey: 'usa', years: '2003-present',
      displacement: '5.7 L · 5,654 cc', layout: 'V8 · OHV · 16V', fuelKey: 'petrol', aspirationKey: 'naturallyAspirated',
      injectionKey: 'multiPointInjection', blockKey: 'castIronBlock', timingKey: 'timingChain',
      applications: ['Ram 1500', 'Dodge Charger / Challenger / Durango', 'Chrysler 300', 'Jeep Grand Cherokee'], consumption: '12-19 L/100 km',
      declaredLifeKey: 'notPublished', typicalLife: '250,000-400,000 km', oilRecord: '', statusKey: 'generationCritical',
      text: {
        en: { construction: 'Iron-block 5.7-litre pushrod V8 with aluminium heads, multipoint injection, timing chain and MDS cylinder deactivation on many versions; 2009 Eagle update added variable timing.', issues: 'Lifter and cam wear; exhaust-manifold bolt breakage; MDS-related concerns; valve-seat issues on some early engines; oil leaks and cooling neglect.', pros: 'Strong sound and torque, simple compact V8 layout, broad parts supply and large enthusiast base.', cons: 'Fuel use is high; idle history, oil pressure and lifter noise matter, and pre-2009 and Eagle versions differ.' },
        es: { construction: 'V8 5.7 de bloque de hierro, varillas, culatas de aluminio, inyección multipunto, cadena y MDS; Eagle 2009 añade distribución variable.', issues: 'Taqués y levas; tornillos de escape; problemas MDS; asientos de válvula tempranos; fugas y refrigeración.', pros: 'Buen sonido y par, V8 compacto sencillo, muchas piezas y comunidad.', cons: 'Consumo alto; importan horas al ralentí, presión de aceite y ruido de taqués; versiones cambian desde 2009.' },
        fr: { construction: 'V8 5,7 litres bloc fonte à tiges, culasses aluminium, injection multipoint, chaîne et MDS ; mise à jour Eagle 2009 avec calage variable.', issues: 'Poussoirs et cames ; vis de collecteur ; soucis MDS ; sièges de soupapes précoces ; fuites et refroidissement.', pros: 'Son et couple forts, V8 compact simple, pièces nombreuses et grande communauté.', cons: 'Consommation élevée ; ralenti, pression d’huile et bruit poussoirs comptent ; versions différentes après 2009.' },
        de: { construction: '5,7-Liter-Grauguss-Stößelstangen-V8 mit Aluminiumköpfen, MPI, Kette und oft MDS; Eagle-Update 2009 mit variabler Steuerung.', issues: 'Stößel- und Nockenverschleiß; Krümmerbolzen; MDS-Themen; frühe Ventilsitze; Öllecks und Kühlungsvernachlässigung.', pros: 'Starker Klang und Drehmoment, kompakter einfacher V8, viele Teile und große Community.', cons: 'Hoher Verbrauch; Leerlaufhistorie, Öldruck und Stößelgeräusch zählen; Vor-2009 und Eagle unterscheiden sich.' }
      }
    }
  ]
};
