import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

export const ROOT_DIR = fileURLToPath(new URL('../../', import.meta.url));
export const LEGACY_CANONICAL_PATH = path.join(ROOT_DIR, 'data', 'engines', 'canonical.json');
export const ENGINE_DATA_PATH = path.join(ROOT_DIR, 'engine-data.js');
export const REGIONS_DIR = path.join(ROOT_DIR, 'data', 'engines');
export const SOURCE_DIR = path.join(REGIONS_DIR, 'source');
export const SOURCE_REGIONS_DIR = path.join(SOURCE_DIR, 'regions');
export const SOURCE_SCHEMA_PATH = path.join(SOURCE_DIR, 'schema.json');
export const REGIONS = ['europe', 'japan', 'korea', 'usa'];
export const LANGUAGES = ['en', 'es', 'fr', 'de'];
export const VERIFIED_ENGINE_ID = 'volvo-b5202s';

export function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

export function writeText(filePath, content) {
  fs.writeFileSync(filePath, content, 'utf8');
}

export function sourceRegionFilePath(region) {
  return path.join(SOURCE_REGIONS_DIR, `${region}.json`);
}

export function readSourceRegion(region) {
  return JSON.parse(readText(sourceRegionFilePath(region)));
}

export function readSourceData() {
  const regionFiles = REGIONS.map((region) => readSourceRegion(region));
  return {
    schemaVersion: 1,
    regions: REGIONS,
    regionFiles,
    records: regionFiles.flatMap((sourceFile) => sourceFile.records || [])
  };
}

export function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function generatedHeader() {
  return [
    '/*',
    ' * Generated from data/engines/source/regions/*.json by npm run engines:generate.',
    ' * Do not edit this file directly.',
    ' */',
    ''
  ].join('\n');
}

export function buildMonolithicJs(records) {
  return `${generatedHeader()}window.AUTOHUB_ENGINE_DATA = {\n  records: ${JSON.stringify(records, null, 2)}\n};\n`;
}

export function buildRegionalJs(region, records) {
  return `${generatedHeader()}window.AUTOHUB_ENGINE_DATA_REGIONS = window.AUTOHUB_ENGINE_DATA_REGIONS || {};\nwindow.AUTOHUB_ENGINE_DATA_REGIONS.${region} = ${JSON.stringify(records, null, 2)};\n`;
}

export function regionFilePath(region) {
  return path.join(REGIONS_DIR, `${region}.js`);
}

export function generatedOutputs(sourceData) {
  const records = sourceData.records || [];
  const outputs = new Map();
  outputs.set(ENGINE_DATA_PATH, buildMonolithicJs(records));
  for (const region of REGIONS) {
    const sourceFile = (sourceData.regionFiles || []).find((item) => item.region === region);
    outputs.set(regionFilePath(region), buildRegionalJs(region, sourceFile?.records || []));
  }
  return outputs;
}

export function loadBrowserGlobal(jsText, filename = 'inline.js', context = { window: {} }) {
  vm.runInNewContext(jsText, context, { filename });
  return context;
}

export function loadMonolithicRecords(filePath = ENGINE_DATA_PATH) {
  const context = loadBrowserGlobal(readText(filePath), filePath);
  return context.window.AUTOHUB_ENGINE_DATA?.records || [];
}

export function loadRegionalRecords() {
  const context = { window: {} };
  for (const region of REGIONS) {
    loadBrowserGlobal(readText(regionFilePath(region)), regionFilePath(region), context);
  }
  return context.window.AUTOHUB_ENGINE_DATA_REGIONS || {};
}

export function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

export function normalizeForLegacy(record) {
  const normalized = deepClone(record);
  delete normalized.verification;
  return normalized;
}

export function sortObjectKeys(value) {
  if (Array.isArray(value)) return value.map(sortObjectKeys);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.keys(value).sort().map((key) => [key, sortObjectKeys(value[key])]));
}

export function canonicalFingerprint(value) {
  return JSON.stringify(sortObjectKeys(value));
}

export function assertCondition(condition, message, errors) {
  if (!condition) errors.push(message);
}

export function formatCounts(records) {
  return Object.fromEntries(REGIONS.map((region) => [
    region,
    records.filter((record) => record.regionKey === region).length
  ]));
}
